# Generated by Django 4.2.7 on 2023-11-17 01:21

import accounts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('articles', '0002_article_ref_movie_comment'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='dislikes_articles',
            field=models.ManyToManyField(related_name='disliked_users', to='articles.article'),
        ),
        migrations.AddField(
            model_name='user',
            name='dislikes_movies',
            field=models.ManyToManyField(related_name='disliked_users', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='user',
            name='followings',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='introduce',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='likes_articles',
            field=models.ManyToManyField(related_name='liked_users', to='articles.article'),
        ),
        migrations.AddField(
            model_name='user',
            name='likes_comments',
            field=models.ManyToManyField(related_name='liked_users', to='articles.comment'),
        ),
        migrations.AddField(
            model_name='user',
            name='likes_movies',
            field=models.ManyToManyField(related_name='liked_users', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='user',
            name='likes_reviews',
            field=models.ManyToManyField(related_name='liked_users', to='movies.review'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to=accounts.models.User.user_directory_path),
        ),
    ]
