# Generated by Django 4.2.7 on 2023-11-17 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('articles', '0001_initial'),
        ('movies', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dislikes_articles',
            field=models.ManyToManyField(related_name='disliked_users', to='articles.article'),
        ),
        migrations.AddField(
            model_name='profile',
            name='dislikes_movies',
            field=models.ManyToManyField(related_name='disliked_users', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='profile',
            name='followings',
            field=models.ManyToManyField(related_name='followers', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='likes_articles',
            field=models.ManyToManyField(related_name='liked_users', to='articles.article'),
        ),
        migrations.AddField(
            model_name='profile',
            name='likes_comments',
            field=models.ManyToManyField(related_name='liked_users', to='articles.comment'),
        ),
        migrations.AddField(
            model_name='profile',
            name='likes_movies',
            field=models.ManyToManyField(related_name='liked_users', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='profile',
            name='likes_reviews',
            field=models.ManyToManyField(related_name='liked_users', to='movies.review'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='wishes_movies',
            field=models.ManyToManyField(related_name='wished_users', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
