# Generated by Django 4.2.7 on 2023-11-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_rating_avg_movie_rating_cnt_and_more'),
        ('accounts', '0002_remove_user_age_user_dislikes_articles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wishes_movies',
            field=models.ManyToManyField(related_name='wished_users', to='movies.movie'),
        ),
    ]
